name: CI

on:
  pull_request:
    branches: [ yeezy-com ]
  workflow_dispatch:

jobs:
  test:
    name: 프로젝트 빌드
    runs-on: ubuntu-latest

    steps:
      - name: 레포지토리 불러오기
        uses: actions/checkout@v4

      - name: JDK 21 설정
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'openjdk'
          cache: 'gradle'

      - name: gradlew 실행 권한 부여
        run: chmod +x gradlew

      - name: 프로젝트 gradlew 빌드
        run: ./gradlew build

      - name: 테스트 결과 보고서 작성
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: 테스트 결과
          path: backend/build/test-results/test/*.xml
          reporter: java-junit
